from __future__ import annotations

import ast
import glob
import os
import re
from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Tuple

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from scipy.special import expit
from scipy.stats import chi2
from scipy.stats import norm
from scipy.stats import shapiro
from scipy.stats import skew
from scipy.stats import t as student_t
from scipy.stats import ttest_rel

import common
from custom_logger import CustomLogger

import warnings


ADVANCED_STATS_SPECIFICATION = "reviewer_response_v4_bounded_common_window"

import statsmodels.api as sm
import statsmodels.formula.api as smf
from patsy import build_design_matrices, dmatrix
from statsmodels.tools.sm_exceptions import ConvergenceWarning


# Create a module level logger so every save and model fitting step is traceable.
logger = CustomLogger(__name__)


# Use a dedicated dataclass so statistical results can move cleanly between
# computations, tables, and plots without relying on positional tuples.

from .results import TOSTResult
from ..utils.parsing import parse_numeric_list
from ..utils.distance import distance_code_to_metres, distance_codes_to_metres, validate_distances_metres


class RunnerMixin:
    """Focused method group extracted without changing calculation logic."""

    def run_all(self, trial_df: pd.DataFrame, equivalence_margin: float = 5.0, trigger_threshold: float = 0.05) -> Dict[str, pd.DataFrame]:

        """Run the full advanced statistics pipeline end to end.

        Args:
            trial_df: Trial level input DataFrame.
            equivalence_margin: Symmetric equivalence margin used in the
                near versus far TOST comparison.
            trigger_threshold: Threshold on the 0..1 pressure-sensitive trigger
                signal used to define a binary pressed/risk state.

        Returns:
            A dictionary containing the main intermediate and final result
            tables generated by the pipeline.
        """
        # Log the start of the end to end pipeline for traceability.
        logger.info("Starting advanced statistics pipeline")
        logger.info(
            "Advanced statistics specification: "
            f"{ADVANCED_STATS_SPECIFICATION}"
        )
        logger.info(
            "Common event-aligned trigger window: "
            f"{self.common_window_pre_s:.2f} s before participant passage to "
            f"{self.common_window_post_s:.2f} s after passage."
        )
        # Step 1: derive participant by video trigger features.
        feature_df = self.build_trigger_feature_table(threshold=trigger_threshold)
        enriched_trial_df = self.merge_trigger_features(
            trial_df,
            feature_df=feature_df,
            save=True,
        )
        # Generate and verify the primary manuscript figure before model fitting
        # so it remains available even if a later statistical model fails.
        logger.info(
            "Generating perceived_unsafety_common_window_full_factorial in "
            f"'{self.output_dir}' and '{self.fig_dir}'."
        )
        common_window_figure_summary = (
            self.create_common_window_figure_with_uncertainty(enriched_trial_df)
        )
        # Step 2: fit the primary bounded model. Participant-clustered sandwich
        # uncertainty allows arbitrary dependence among a participant's trial
        # totals, including the effect of serially dependent trigger bins.
        common_window_binomial = self.run_primary_grouped_binomial_analysis(
            enriched_trial_df,
            analysis_label="common_window_primary",
            success_column="unsafe_bins_common_window",
            valid_column="valid_bins_common_window",
            model_mode="full",
        )
        participant_first_binomial = self.run_primary_grouped_binomial_analysis(
            enriched_trial_df,
            analysis_label="common_window_participant_first",
            success_column="unsafe_bins_common_window",
            valid_column="valid_bins_common_window",
            model_mode="participant_first",
        )

        # Event-aligned sensitivity analyses use only yielding trials in the
        # participant-first subset, where spacing is not confounded with the
        # avatar-first participant-passage geometry.
        event_results: Dict[str, Dict[str, pd.DataFrame]] = {}
        for event_name in (
            "braking_onset_window",
            "stopping_window",
            "resumption_window",
        ):
            event_results[event_name] = self.run_primary_grouped_binomial_analysis(
                enriched_trial_df,
                analysis_label=f"{event_name}_participant_first",
                success_column=f"{event_name}_unsafe_bins",
                valid_column=f"{event_name}_valid_bins",
                model_mode="event_participant_first_yielding",
            )

        # Repeat the new primary common-window model at every configured trigger
        # threshold. This is distinct from the superseded legacy-window check.
        threshold_results: Dict[str, Dict[str, pd.DataFrame]] = {}
        configured_thresholds = [
            float(value)
            for value in self._config_or_default(
                "trigger_threshold", [trigger_threshold]
            )
        ]
        for current_threshold in configured_thresholds:
            threshold_key = f"{int(round(current_threshold * 100)):02d}pct"
            if np.isclose(current_threshold, trigger_threshold):
                threshold_results[threshold_key] = common_window_binomial
                continue
            threshold_features = self.build_trigger_feature_table(
                threshold=current_threshold
            )
            threshold_trials = self.merge_trigger_features(
                trial_df,
                feature_df=threshold_features,
                save=False,
            )
            threshold_results[threshold_key] = self.run_primary_grouped_binomial_analysis(
                threshold_trials,
                analysis_label=f"common_window_threshold_{threshold_key}",
                success_column="unsafe_bins_common_window",
                valid_column="valid_bins_common_window",
                model_mode="full",
            )
        for table_key, filename in (
            ("marginal_probabilities", "common_window_threshold_marginal_probabilities.csv"),
            ("revised_contrasts", "common_window_threshold_revised_contrasts.csv"),
            ("omnibus_tests", "common_window_threshold_omnibus_tests.csv"),
            ("diagnostics", "common_window_threshold_binomial_diagnostics.csv"),
        ):
            frames = [
                result[table_key]
                for result in threshold_results.values()
                if not result[table_key].empty
            ]
            if frames:
                self._save_table(pd.concat(frames, ignore_index=True), filename)

        # Retain the Gaussian repeated-measures fit only as a secondary model
        # sensitivity analysis; it is no longer the primary inference.
        common_window_gaussian = self.run_improved_repeated_measures_model(
            enriched_trial_df,
            outcome="perceived_unsafety_common_window_pct",
            analysis_label="common_window_gaussian_secondary",
        )
        common_window_quality = self.summarise_common_window_quality(
            enriched_trial_df
        )
        common_window_descriptives = self.create_common_window_participant_descriptives(
            enriched_trial_df
        )
        # Step 3: test near versus far equivalence on the legacy-window data.
        # This remains a secondary exploratory output for continuity.
        equivalence_df = self.run_equivalence_tests(
            enriched_trial_df,
            outcome="crossing_risk",
            equivalence_margin=equivalence_margin,
        )
        # Step 4: fit the trigger feature models and export their figures.
        feature_coef_df = self.run_feature_models_and_figures(enriched_trial_df)
        # Step 5: fit the within versus between participant rating models.
        within_between_df = self.run_within_between_models(enriched_trial_df)
        logger.info("Finished advanced statistics pipeline")
        # Return all major outputs so callers can inspect or reuse them programmatically.
        return {
            "features": feature_df,
            "trial_enriched": enriched_trial_df,
            "common_window_binomial_coefficients": common_window_binomial["coefficients"],
            "common_window_marginal_probabilities": common_window_binomial["marginal_probabilities"],
            "common_window_revised_contrasts": common_window_binomial["revised_contrasts"],
            "common_window_omnibus_tests": common_window_binomial["omnibus_tests"],
            "common_window_binomial_diagnostics": common_window_binomial["diagnostics"],
            "participant_first_binomial": participant_first_binomial,
            "event_aligned_binomial": event_results,
            "threshold_binomial": threshold_results,
            "common_window_gaussian_secondary": common_window_gaussian,
            "common_window_quality": common_window_quality,
            "common_window_participant_descriptives": common_window_descriptives,
            "common_window_figure_summary": common_window_figure_summary,
            "equivalence": equivalence_df,
            "feature_coefficients": feature_coef_df,
            "within_between": within_between_df,
        }
